### ISSUE TITLE
QFG1VGA: recompile all fails on few scripts

### ISSUE THREAD

**Issue by ZvikaZ** [Kawa-oneechan/SCICompanion#12]
Clean copy of QFG1VGA, decompile, and then 'compile all', fails on few scripts.
I have already reported (https://github.com/Kawa-oneechan/SCICompanion/issues/11) about the problem at Rock.sc, but there are few more failures:

	Error: (rm43.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 56, col: 27
	Error: (Rock.sc) Duplicate label 'code_0448'  Line: 145, col: 0
	Error: (Rock.sc) Duplicate label 'code_0453'  Line: 152, col: 0
	Error: (RTRandCycle.sc) modeless is a property.  Only one parameter may be supplied.  Line: 525, col: 13
	Error: (chAlloc.sc) The rest modifier must be followed by a parameter name.  Line: 32, col: 9
	Error: (chAlloc.sc) The rest modifier must be followed by a parameter name.  Line: 46, col: 9
	Error: (inputBox.sc) Undeclared identifier '--UNKNOWN-PROP-NAME--' .  Line: 1262, col: 32
	Error: (inputBox_216.sc) Undeclared identifier '--UNKNOWN-PROP-NAME--' .  Line: 330, col: 32
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 416, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 419, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 551, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 554, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 595, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 598, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 748, col: 29
	Error: (rm330.sc) &rest cannot be used if the send target itself contains nested procedure calls or sends. Assign the result of the procedure call or send to a temporary variable and use that instead.  Line: 751, col: 29

**Comment by Kawa-oneechan** [comment]
Why couldn't you just post this as a reply to that issue instead of opening a new one?

**Comment by ZvikaZ** [comment]
> Why couldn't you just post this as a reply to that issue instead of opening a new one?

OK, you're right.
Copying it over there, closing this one.
