### ISSUE TITLE
Crash when decompiling Torin

### ISSUE THREAD

**Issue by ZvikaZ** [Kawa-oneechan/SCICompanion#2]
Hi.
With the latest release, when I decompile Torin's Passage, it crashes in the middle.
With the release I downloaded 2 days ago, it's working OK.

**Comment by Kawa-oneechan** [comment]
Script 64984 `RegionPath` confirmed to break in latest build and work in older. Looking into it now...

**Comment by Kawa-oneechan** [comment]
It tried to look up the name of an opcode that didn't exist, number 130, returning an invalid string pointer that it'd then try to use in formatting the decompiler's progress. Or so I believe it'd be used. In some builds that may be Phil's `ldm` and all is good, or some other *coincidentally* valid data is hit.

Solution: add an extra (fake) opcode name at the end of the list. `RegionPath` now decompiles at a 100% completion rate, and there's no trace of our mysterious 130th opcode if you disassemble it.

Another issue that *also* hits on that same script is that the earlier `ScriptID` "unsigned only" change breaks when the argument is not a number: `(if (not ((ScriptID theRegion) keep?))` does not use a numerical constant as the argument, and I didn't check for that. I only assumed there'd be *at least* one argument.

A new build is now uploading to the usual place.

**Comment by ZvikaZ** [comment]
Fixed, thanks!
