### ISSUE TITLE
`View - Export - Loop as image` with alpha channel

### ISSUE THREAD

**Issue by cdb-boop** [Kawa-oneechan/SCICompanion#25]
When exporting a View resource with `View - Export - Loop as image`, selecting `.png`, `.tif` or `.gif` results in image files that do not have an alpha channel as the background, as opposed to `View - Export - Loop as animated gif`, which does export with an alpha channel.

This is an issue as the background could be the same color as part of the animation.

My current workaround is to export as an animated gif which does export with a transparent background and then extract the desired frames. However, this can result in a scaled-down gif if there are multiple cels with different dimensions (which I believe is a separate [bug](https://github.com/Kawa-oneechan/SCICompanion/issues/26)).

**Comment by Kawa-oneechan** [comment]
Okay so let's clear something up first.

One: there is, in this context, no such thing as an alpha channel. The files use a palette, one entry of which may be assigned to be transparent. Usually that's the first one.

Two: in an SCI view resource, each individual frame can have its own key color. The animated gif exporter naively picks the first cel's key color and uses it throughout, assuming that for most animations the whole loop will share the same key. I tested it just now by changing one of them.

Three: exporting a whole sheet (the entire view _or_ a single loop) would run afoul of the same problem. While png supports having more than one key color, individual cels may use that same color for non-transparent pixels. That is in fact one reason for a single view to have more than one key color.

Four: if your art program does not distinguish colors by index, only by value, and the key color for your export happens to for whatever god-fearing reason exactly match another, I feel bad for you but that's not on SCI Companion to fix.

Understanding at least the first three points, do you still have an issue?

**Comment by cdb-boop** [comment]
Yes, I figured there was no actual alpha channel. I guess I was just confused by the different results between the two export methods. I guess I can work around it. Thanks.
