### ISSUE TITLE
`View - Export - Loop as animated gif` image not always full size

### ISSUE THREAD

**Issue by cdb-boop** [Kawa-oneechan/SCICompanion#26]
When exporting a View animation a `.gif` using `View - Export - Loop as animated gif`, the resulting image file may be smaller than expected. It appears to me that the program may be naively taking the size of the first cel. (This behavior is also present in the Sierra Viewer.)

I was expecting the resulting gif to be saved using the max dimensions over all the cels. By contrast, `View - Export - Loop as image` appears to respect just the max height of the cels.

For example, here are the actual and expected dimensions for `View.12200` from the lsl7demo.

| | Width  | Height |
| ------------- | ------------- | ------------- |
| Min Cel Dimensions | 60 | 18 |
| Max Cel Dimensions | 375 | 310 |
| First Cel Dimensions | 71 | 18 |
| `View - Export - Loop as animated gif` | 71 | 18 |
| `View - Export - Loop as image` | 6025 | 310 |
| Expected `Loop as animated gif` | 375 | 310 |
| Expected `Loop as image` | 7125 = 375 * 19 cels | 310 |

**Comment by Kawa-oneechan** [comment]
Could not reproduce. I extracted view 12200 and extracted loop 2. The gif is as big as the loop's biggest cel and everything is lined up as it should be.

![View12200-2](https://github.com/user-attachments/assets/e5a54802-6c0b-4f1f-a9bc-c2bbdd6df86e)

**Comment by cdb-boop** [comment]
Sorry, you are absolutely right. The Windows Photos app is displaying it completely wrong.
