### ISSUE TITLE
SQ3 decompilation crashed

### ISSUE THREAD

**Issue by ZvikaZ** [Kawa-oneechan/SCICompanion#3]
Hi.

SQ3 crashes when trying to decompile.

Before fixing this, maybe it's possible to print some error message before it crashes out?

Thanks

**Comment by Kawa-oneechan** [comment]
Could reproduce easily in the 2018-10-21 build of SCI Companion, crashing in the "analyzing control flow" phase for script 0.

However, the [2020-04-24 build](http://helmet.kafuka.org/sci/SCICompanion.exe) just finished the task with a 98% success rate.

**Comment by ZvikaZ** [comment]
Indeed, I've used an older release.
Thanks for all the help!
