### ISSUE TITLE
Companion does not display properly in high resolutions

### ISSUE THREAD

**Issue by EricOakford** [Kawa-oneechan/SCICompanion#7]
I have just upgraded to a ThinkPad 490, and its native resolution (2560x1440) is not properly supported by SCICompanion - the buttons are much too small, and the text doesn't fit. Previously, I was using 1600x900, and Companion displayed fine. Here is a screenshot.
![2020-07-31](https://user-images.githubusercontent.com/3394072/89092005-0c0ff800-d37c-11ea-9e42-d23b5fd9d351.png)
In contrast, WinAGI runs fine. At least for now, I can just switch to 1600x900 when using Companion.

**Comment by Kawa-oneechan** [comment]
This seems to be a DPI thing. I only have 1920x1080 myself, at what 10 calls 100% scale -- it recommends 125% but hey it's free real estate. So what I'd like to know is your DPI setting when you're on 2560x1440 and 1600x900 alike.

Now, according to the application manifest, SCI Companion claims it is DPI aware. So here's a copy I whipped up that does not make that claim. Does that work any better for you? Mind you, tiny text that *fits* is better than big text that doesn't fit, in my book.

[SCICompanion-no-dpi-awareness.zip](https://github.com/Kawa-oneechan/SCICompanion/files/5010032/SCICompanion-no-dpi-awareness.zip)

**Comment by EricOakford** [comment]
Okay, it seems to work better.
The scale and layout setting is 200% in 2560x1440, and 125% in 1600x900.
I also figured out that you can override the DPI scaling behavior in the Compatibility tab. Selecting "System (Enhanced)" fixed the problem.

**Comment by Kawa-oneechan** [comment]
Except apparently the manifest claim that SCI Companion is DPI aware is apparently a lie and I suppose the problem is just not *as bad* at 125% :thinking:

Fit to commit?

**Comment by EricOakford** [comment]
Might as well be honest about it.
