### ISSUE TITLE
GK1 decompilation crashes

### ISSUE THREAD

**Issue by ZvikaZ** [Kawa-oneechan/SCICompanion#8]
Hi.

I'm trying to decompile GK1 with latest version (from Kawa's stash), and it crashes in the middle.
With older version it worked well.

Thanks.

**Comment by Kawa-oneechan** [comment]
It was my hack to make the LSL3 demo decompile correctly. Easy to believe, really.

**Comment by Kawa-oneechan** [comment]
New build is now available from the Stash that managed to decompile GK1 (disk version) without crashing on the `Str` class *as well* as the LSL3 demo (if given the real game's selector vocab) without thinking every selector is `species`.

If you could please confirm this on your side...

**Comment by ZvikaZ** [comment]
It's indeed working (on GK1).
Congratulations for the new look.

Thanks.
